name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: maxheld83/r-ci:d2a3a47
      env:
        ENV R_LIBS_WORKFLOW: /github/home/lib/R/library/
        # location for R libraries which should persist only for this action
        ENV R_LIBS_ACTION: $R_LIBS_DEV_HELPERS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install System Dependencies
        run: |
            sudo apt-get update --allow-releaseinfo-change \
            && sudo apt-get install -y --no-install-recommends \
            libxml2-dev \
            libssl-dev \
            git \
            && apt-get clean -y
      - name: Install package dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check package
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
