'on':
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: rstudio/r-base:3.6-xenial
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install System Dependencies
        run: |
            sudo apt-get update && apt-get install -y --no-install-recommends \
            docker \
            git \
            libxml2-dev \
            libssl-dev \
            && apt-get clean -y \
            && curl -fsSL https://get.docker.com -o get-docker.sh \
            && sh get-docker.sh
      - name: Install package dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check package
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
      - name: Document Package
        run: |
          Rscript -e "pkgdown::build_site(override = list(devel = FALSE, external = FALSE))"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
