name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: maxheld83/r-ci:d2a3a47
      env:
        ENV R_LIBS_WORKFLOW: /github/home/lib/R/library/
        # location for R libraries which should persist only for this action
        ENV R_LIBS_ACTION: $R_LIBS_DEV_HELPERS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Authenticate GCP
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Download Cache
        uses: actions/gcloud/cli@master
        with:
          entrypoint: gsutil
          args: -m cp -r gs://ghactions-cache/lib.tar.gz /github/home/
      - name: Decompress Cache
        uses: actions/bin/sh@5968b3a61ecdca99746eddfdc3b3aab7dc39ea31
        with:
          entrypoint: tar
          args: --extract --ungzip --file /github/home/lib.tar.gz --directory /github/home
      - name: Show Cache
        run: ls -a /github/home
      - name: Install System Dependencies
        run: |
            apt-get update --allow-releaseinfo-change \
            && apt-get install -y --no-install-recommends \
            docker \
            git \
            libxml2-dev \
            libssl-dev \
            && apt-get clean -y
      - name: Install package dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check package
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
